#!/usr/bin/env node
/**
 * Pulls the BookPass design file out of Figma.
 *
 * Writes three things into design/figma/:
 *   file.json       the raw document tree, for exact colours and measurements
 *   frames/*.png    every top-level frame, rendered
 *   SUMMARY.md      a readable index of pages and frames
 *
 * Usage:
 *   1. Create a read-only token at
 *      Figma → Settings → Security → Personal access tokens
 *      (scope: file_content:read)
 *   2. Put it in .env.local, which is gitignored:
 *        FIGMA_TOKEN=figd_xxxxxxxxxxxx
 *   3. npm run figma:pull
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { Buffer } from 'node:buffer';
import path from 'node:path';

const FILE_KEY = process.env.FIGMA_FILE_KEY ?? 'bTTCVrPWNEV6MIXfmuaVmf';
const OUT_DIR = path.join('design', 'figma');
const FRAME_DIR = path.join(OUT_DIR, 'frames');
const IMAGE_SCALE = 2;
const IMAGE_BATCH = 20;

async function loadToken() {
  if (process.env.FIGMA_TOKEN) {
    return process.env.FIGMA_TOKEN.trim();
  }

  try {
    const env = await readFile('.env.local', 'utf8');
    const match = env.match(/^\s*FIGMA_TOKEN\s*=\s*(.+)$/m);
    if (match) {
      return match[1].trim().replace(/^["']|["']$/g, '');
    }
  } catch {
    // .env.local is optional; fall through to the error below.
  }

  throw new Error(
    'No Figma token found.\n' +
      'Add this line to .env.local (gitignored):\n\n' +
      '  FIGMA_TOKEN=figd_your_token_here\n'
  );
}

async function figmaGet(token, url) {
  const response = await fetch(url, { headers: { 'X-Figma-Token': token } });

  if (!response.ok) {
    const body = await response.text();
    const hint =
      response.status === 403
        ? '\nA 403 usually means the token lacks file_content:read scope, or it cannot see this file.'
        : response.status === 404
          ? '\nA 404 usually means the file key is wrong.'
          : '';
    throw new Error(`Figma responded ${response.status} ${response.statusText}${hint}\n${body}`);
  }

  return response.json();
}

/** Every CANVAS node is a page; its direct children are the frames we care about. */
function collectFrames(document) {
  const pages = [];

  for (const page of document.children ?? []) {
    if (page.type !== 'CANVAS') continue;

    const frames = (page.children ?? [])
      .filter((node) => node.type === 'FRAME' || node.type === 'COMPONENT')
      .map((node) => ({
        id: node.id,
        name: node.name,
        type: node.type,
        width: Math.round(node.absoluteBoundingBox?.width ?? 0),
        height: Math.round(node.absoluteBoundingBox?.height ?? 0),
      }));

    pages.push({ id: page.id, name: page.name, frames });
  }

  return pages;
}

function chunk(items, size) {
  const out = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

/** Figma renders asynchronously and hands back short-lived S3 URLs. */
async function fetchFrameImages(token, frameIds) {
  const urls = new Map();

  for (const batch of chunk(frameIds, IMAGE_BATCH)) {
    const endpoint =
      `https://api.figma.com/v1/images/${FILE_KEY}` +
      `?ids=${batch.join(',')}&format=png&scale=${IMAGE_SCALE}`;
    const { images, err } = await figmaGet(token, endpoint);

    if (err) {
      throw new Error(`Figma could not render frames: ${err}`);
    }
    for (const [id, url] of Object.entries(images ?? {})) {
      if (url) urls.set(id, url);
    }
  }

  return urls;
}

/** Turns "02 · Sign Up / Create Account" into "02-sign-up-create-account". */
function toFileName(name) {
  const slug = name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60);
  return slug || 'frame';
}

async function downloadFrames(pages, urls) {
  const saved = [];
  const seen = new Set();

  for (const page of pages) {
    for (const frame of page.frames) {
      const url = urls.get(frame.id);
      if (!url) continue;

      let name = toFileName(frame.name);
      while (seen.has(name)) name = `${name}-2`;
      seen.add(name);

      const response = await fetch(url);
      if (!response.ok) {
        console.warn(`  ! could not download "${frame.name}" (${response.status})`);
        continue;
      }

      const file = path.join(FRAME_DIR, `${name}.png`);
      await writeFile(file, Buffer.from(await response.arrayBuffer()));
      saved.push({ ...frame, file });
    }
  }

  return saved;
}

function buildSummary(file, pages, saved) {
  const byId = new Map(saved.map((frame) => [frame.id, frame]));
  const lines = [
    `# ${file.name}`,
    '',
    `Pulled from Figma on ${new Date().toISOString().slice(0, 10)}.`,
    `Last modified in Figma: ${file.lastModified}`,
    '',
    'Generated by `npm run figma:pull` — do not edit by hand.',
    '',
  ];

  for (const page of pages) {
    lines.push(`## ${page.name}`, '');

    if (page.frames.length === 0) {
      lines.push('_No top-level frames._', '');
      continue;
    }

    lines.push('| Frame | Size | Render |', '| --- | --- | --- |');
    for (const frame of page.frames) {
      const rendered = byId.get(frame.id);
      const link = rendered
        ? `[png](${path.relative(OUT_DIR, rendered.file).split(path.sep).join('/')})`
        : '—';
      lines.push(`| ${frame.name} | ${frame.width}×${frame.height} | ${link} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

async function main() {
  const token = await loadToken();

  await mkdir(FRAME_DIR, { recursive: true });

  console.log(`Fetching file ${FILE_KEY}…`);
  const file = await figmaGet(token, `https://api.figma.com/v1/files/${FILE_KEY}`);
  await writeFile(path.join(OUT_DIR, 'file.json'), JSON.stringify(file, null, 2));

  const pages = collectFrames(file.document);
  const frameIds = pages.flatMap((page) => page.frames.map((frame) => frame.id));

  console.log(`  "${file.name}" — ${pages.length} pages, ${frameIds.length} top-level frames`);

  if (frameIds.length > 0) {
    console.log('Rendering frames…');
    const urls = await fetchFrameImages(token, frameIds);
    const saved = await downloadFrames(pages, urls);
    await writeFile(path.join(OUT_DIR, 'SUMMARY.md'), buildSummary(file, pages, saved));
    console.log(`  saved ${saved.length} PNGs to ${FRAME_DIR}`);
  } else {
    await writeFile(path.join(OUT_DIR, 'SUMMARY.md'), buildSummary(file, pages, []));
  }

  console.log(`Done. See ${path.join(OUT_DIR, 'SUMMARY.md')}`);
}

main().catch((error) => {
  console.error(`\n${error.message}`);
  process.exit(1);
});
